spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/quiz_platform?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
