spring:
  datasource:
    url: jdbc:h2:mem:quizplatform
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

quiz-platform:
  security:
    jwt:
      issuer: quiz-platform-authenticator
      audience: quiz-platform
      validitytime: 3600 #seconds